spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/database-edu
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console.enabled: true

#liquibase change log file

liquibase:
  change-log: classpath:db/changelog-master.xml
  enabled: true
